version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: monthly
      open-pull-requests-limit: 10
      reviewers:
        - "harshita"
      assignees:
        - "harshita"
      commit-message:
          prefix: "deps"
          include: "scope"
